/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package structurevis.ui;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import structurevis.ranking.RankingAnalyses;
import structurevis.structures.Structure;
import structurevis.structures.StructureParser;
import structurevis.structures.metadata.MetadataFromFile;
import structurevis.structures.metadata.SequenceData1D;
import structurevis.structures.metadata.SequenceData2D;

/**
 *
 * @author Michael
 */
public class ContigencyPanel extends javax.swing.JPanel {

    MainApp mainapp = null;
    ArrayList<SequenceData1D> sequenceData1D = null;
    ArrayList<SequenceData2D> sequenceData2D = null;
    ArrayList sequenceData = new ArrayList();

    /**
     * Creates new form ContigencyPanel
     */
    public ContigencyPanel(MainApp mainapp) {
        initComponents();
        this.mainapp = mainapp;
        //jScrollPane1.setViewportView(rankingTable);

        if (mainapp.structureCollection != null) {
            sequenceData1D = mainapp.structureCollection.sequenceData1D;
            sequenceData2D = mainapp.structureCollection.sequenceData2D;
            sequenceData.addAll(sequenceData1D);
            sequenceData.addAll(sequenceData2D);

            DefaultComboBoxModel sequenceDataModel = new DefaultComboBoxModel();
            dataSourceBox.setModel(sequenceDataModel);

            for (int i = 0; i < sequenceData.size(); i++) {
                sequenceDataModel.addElement(((MetadataFromFile) sequenceData.get(i)).name);
            }
        }
    }

    public static void createAndShowGUI(MainApp mainapp) {
        //Create and set up the window.
        JFrame frame = new JFrame("Structure ranking");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setIconImage(mainapp.appIcon.getImage());

        //Create and set up the content pane.
        ContigencyPanel newContentPane = new ContigencyPanel(mainapp);
        newContentPane.setOpaque(true); //content panes must be opaque
        frame.setContentPane(newContentPane);

        //Display the window.
        frame.pack();
        frame.setVisible(true);
    }

    public static void main(String[] args) {
        //Schedule a job for the event-dispatching thread:
        //creating and showing this application's GUI.
        javax.swing.SwingUtilities.invokeLater(new Runnable() {

            public void run() {
                createAndShowGUI(null);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dataSourceBox = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pc1panel = new javax.swing.JPanel();
        pc1 = new javax.swing.JLabel();
        pc1exp = new javax.swing.JLabel();
        uc1panel = new javax.swing.JPanel();
        uc1 = new javax.swing.JLabel();
        uc1exp = new javax.swing.JLabel();
        ct1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pc2panel = new javax.swing.JPanel();
        pc2 = new javax.swing.JLabel();
        pc2exp = new javax.swing.JLabel();
        uc2panel = new javax.swing.JPanel();
        uc2 = new javax.swing.JLabel();
        uc2_exp = new javax.swing.JLabel();
        ct2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pt1 = new javax.swing.JLabel();
        ut1 = new javax.swing.JLabel();
        tt = new javax.swing.JLabel();

        jLabel1.setText("Data source");

        dataSourceBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataSourceBoxActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(4, 4));
        jPanel1.add(jLabel3);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Paired");
        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Unpaired");
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Total");
        jPanel1.add(jLabel14);

        jLabel6.setText("Category 1");
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6);

        pc1panel.add(pc1);
        pc1panel.add(pc1exp);

        jPanel1.add(pc1panel);

        uc1panel.add(uc1);
        uc1panel.add(uc1exp);

        jPanel1.add(uc1panel);

        ct1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(ct1);

        jLabel12.setText("Category 2");
        jLabel12.setOpaque(true);
        jPanel1.add(jLabel12);

        pc2panel.add(pc2);
        pc2panel.add(pc2exp);

        jPanel1.add(pc2panel);

        uc2panel.add(uc2);
        uc2panel.add(uc2_exp);

        jPanel1.add(uc2panel);

        ct2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(ct2);

        jLabel11.setText("Total");
        jPanel1.add(jLabel11);

        pt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(pt1);

        ut1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(ut1);

        tt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addGap(8, 8, 8)
                        .addComponent(dataSourceBox, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataSourceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dataSourceBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataSourceBoxActionPerformed
        int index = dataSourceBox.getSelectedIndex();
        if (index != -1) {
            Object data = sequenceData.get(index);
            double cutoff = 1;
            if (data instanceof SequenceData1D) {
                SequenceData1D sequenceData1D = (SequenceData1D) data;
                Structure s = StructureParser.parseDotBracketString(mainapp.structureCollection.dotBracketStructure);

                ArrayList<Double> paired = RankingAnalyses.getValues(sequenceData1D, 0, s.length, false, s, true, false, s.length);
                ArrayList<Double> unpaired = RankingAnalyses.getValues(sequenceData1D, 0, s.length, false, s, false, true, s.length);

                int[][] contigency = new int[2][2];

                //contigency[0][0]
                // int pairedC1count = 0;
                //int pairedC2count = 0;
                // int unpairedC1count = 0;
                //  int unpairedC2count = 0;

                ArrayList<Double> pairedC1 = new ArrayList<Double>();
                ArrayList<Double> pairedC2 = new ArrayList<Double>();
                ArrayList<Double> unpairedC1 = new ArrayList<Double>();
                ArrayList<Double> unpairedC2 = new ArrayList<Double>();

                for (int i = 0; i < paired.size(); i++) {
                    if (paired.get(i) < cutoff) {
                        contigency[0][0]++;
                        //pairedC1.add(paired.get(i));
                    } else {
                        contigency[0][1]++;
                        //pairedC2.add(paired.get(i));
                    }
                }

                for (int i = 0; i < unpaired.size(); i++) {
                    if (unpaired.get(i) < cutoff) {
                        contigency[1][0]++;
                        ///unpairedC1.add(unpaired.get(i));
                    } else {
                        contigency[1][1]++;
                        //unpairedC2.add(unpaired.get(i));
                    }
                }

                double pairedTotal = contigency[0][0] + contigency[0][1];
                double c1Total = contigency[0][0] + contigency[1][0];
                double unpairedTotal = contigency[1][0] + contigency[1][1];
                double c2Total = contigency[0][1] + contigency[1][1];
                double total = pairedTotal + unpairedTotal;
                
                double pc1expval = (pairedTotal*c1Total)/total;
                double pc2expval = (pairedTotal*c2Total)/total;
                double uc1expval = (unpairedTotal*c1Total)/total;
                double uc2expval = (unpairedTotal*c2Total)/total;

                pc1.setText(contigency[0][0] + "");
                pc1exp.setText(pc1expval+"");
                pc2.setText(contigency[0][1] + "");
                pc2exp.setText(pc1expval+"");
                pt1.setText(((int) pairedTotal) + "");
                ct1.setText(((int) c1Total) + "");
                uc1.setText(contigency[1][0] + "");
                uc2.setText(contigency[1][1] + "");
                ut1.setText(((int) unpairedTotal) + "");
                ct2.setText(((int) c2Total) + "");
                
                tt.setText(((int) total) + "");



            }
        }
    }//GEN-LAST:event_dataSourceBoxActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ct1;
    private javax.swing.JLabel ct2;
    private javax.swing.JComboBox dataSourceBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pc1;
    private javax.swing.JLabel pc1exp;
    private javax.swing.JPanel pc1panel;
    private javax.swing.JLabel pc2;
    private javax.swing.JLabel pc2exp;
    private javax.swing.JPanel pc2panel;
    private javax.swing.JLabel pt1;
    private javax.swing.JLabel tt;
    private javax.swing.JLabel uc1;
    private javax.swing.JLabel uc1exp;
    private javax.swing.JPanel uc1panel;
    private javax.swing.JLabel uc2;
    private javax.swing.JLabel uc2_exp;
    private javax.swing.JPanel uc2panel;
    private javax.swing.JLabel ut1;
    // End of variables declaration//GEN-END:variables
}
