/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StartupDialog.java
 *
 * Created on 31 Jan 2012, 9:40:41 PM
 */
package structurevis.ui;

import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import structurevis.ui.datacreation.WizardMain;

/**
 *
 * @author Michael Golden
 */
public class StartupDialog extends javax.swing.JDialog {

    MainApp mainapp;
    File lastUsedDataset;

    /**
     * Creates new form StartupDialog
     */
    public StartupDialog(MainApp mainapp) {
        super(mainapp, true);
        this.mainapp = mainapp;
        initComponents();

        lastUsedDataset = mainapp.appPersistence.getLastDatasetUsed();
        if (lastUsedDataset != null && !lastUsedDataset.isDirectory()) {
            lastUsedDataset = lastUsedDataset.getParentFile();
        }
        if (lastUsedDataset == null || !lastUsedDataset.exists()) {
            // use demo dataset
            lastUsedDataset = new File(new File("workspace/HIVShapeExample").getPath());
        }
        jTextField1.setText(lastUsedDataset.getAbsolutePath());
        jTextField1.setCaretPosition(jTextField1.getText().length());

        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - getWidth()) / 2;
        final int y = (screenSize.height - getHeight()) / 2;
        setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        openLastUsed = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        openFromFile = new javax.swing.JButton();
        createNewDaset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Open a dataset");

        openLastUsed.setText("Open");
        openLastUsed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openLastUsedActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);

        jLabel1.setText("Open last used");

        openFromFile.setText("Open dataset from file");
        openFromFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFromFileActionPerformed(evt);
            }
        });
        jPanel1.add(openFromFile);

        createNewDaset.setText("Create a new dataset");
        createNewDaset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewDasetActionPerformed(evt);
            }
        });
        jPanel1.add(createNewDaset);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openLastUsed)
                .addGap(6, 6, 6))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(openLastUsed))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void startLoad() {
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        mainapp.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
    }

    public void endLoad() {
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        mainapp.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        //System.out.println("end");
        //jProgressBar1.setString("");
        //jProgressBar1.setIndeterminate(false);
    }

    private void openLastUsedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openLastUsedActionPerformed
        dispose();
        startLoad();
        if (lastUsedDataset.isDirectory()) {
            mainapp.openStructureCollectionFromFolder(lastUsedDataset);
        } else {
            mainapp.openStructureCollectionFromFile(lastUsedDataset);
        }
        //dispose();
        mainapp.toFront();
        endLoad();
    }//GEN-LAST:event_openLastUsedActionPerformed

    private void openFromFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFromFileActionPerformed
        dispose();
        startLoad();
        int returnVal = mainapp.openDatasetAction();
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            //dispose();
            mainapp.toFront();
        }
        endLoad();
    }//GEN-LAST:event_openFromFileActionPerformed

    private void createNewDasetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewDasetActionPerformed

        new WizardMain().show(mainapp);
        dispose();
        mainapp.toFront();
    }//GEN-LAST:event_createNewDasetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                StartupDialog dialog = new StartupDialog(null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        //System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createNewDaset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton openFromFile;
    private javax.swing.JButton openLastUsed;
    // End of variables declaration//GEN-END:variables
}
